#!/usr/bin/env node
// Regenerates the gallery section of README.md from the theme files, between
// the <!-- GALLERY:START --> and <!-- GALLERY:END --> markers. Themes are
// split into Dark / Light by background luminance and sorted by name.
//
// Usage:
//   node scripts/generate-gallery.mjs           Rewrite the README gallery
//   node scripts/generate-gallery.mjs --check    Verify it is up to date (CI)

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const themesDir = join(root, "themes");
const readmePath = join(root, "README.md");

const checkOnly = process.argv.includes("--check");

const START =
  "<!-- GALLERY:START (auto-generated by scripts/generate-gallery.mjs — do not edit) -->";
const END = "<!-- GALLERY:END -->";

function lin(c) {
  c /= 255;
  return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
}
function luminance(hex) {
  return (
    0.2126 * lin(parseInt(hex.slice(1, 3), 16)) +
    0.7152 * lin(parseInt(hex.slice(3, 5), 16)) +
    0.0722 * lin(parseInt(hex.slice(5, 7), 16))
  );
}
function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const themes = readdirSync(themesDir)
  .filter((f) => f.endsWith(".json") && f !== "index.json")
  .map((f) => {
    const data = JSON.parse(readFileSync(join(themesDir, f), "utf8"));
    return {
      id: f.replace(/\.json$/, ""),
      name: data.name,
      dark: luminance(data.colors.bg) < 0.5,
      style: data.effects?.style ?? null,
    };
  });

function cell(t) {
  if (!t) return "";
  return `[<img src="assets/previews/${t.id}.svg" width="360" alt="${t.name} preview"><br>${t.name}](themes/${t.id}.json)`;
}
function table(list) {
  const sorted = [...list].sort((a, b) => a.name.localeCompare(b.name));
  let out = "| | |\n|:--:|:--:|\n";
  for (let i = 0; i < sorted.length; i += 2) {
    out += `| ${cell(sorted[i])} | ${cell(sorted[i + 1])} |\n`;
  }
  return out;
}

const withFx = themes.filter((t) => t.style);
const classic = themes.filter((t) => !t.style);

const styleGroups = [
  ["Glass", "glass"],
  ["Neumorphism", "neo"],
  ["Skeuomorphism", "skeuo"],
];

const note =
  "> These previews show each theme's glassmorphism, neumorphism, or " +
  "skeuomorphism look. GameSync applies the flat `colors`; the `effects` " +
  "styling is rendered here in the gallery (see " +
  "[Surface effects](#surface-effects-optional)).";

let body = "";
if (withFx.length) {
  body += `### With effects\n\n${note}\n\n`;
  for (const [label, key] of styleGroups) {
    const list = withFx.filter((t) => t.style === key);
    if (list.length) body += `#### ${label}\n\n${table(list)}\n`;
  }
}
body += `### Without effects\n\n`;
body += `#### Dark\n\n${table(classic.filter((t) => t.dark))}\n`;
body += `#### Light\n\n${table(classic.filter((t) => !t.dark))}`;

const block = `${START}\n\n${body}\n${END}`;

const readme = readFileSync(readmePath, "utf8");
const region = new RegExp(escapeRegExp(START) + "[\\s\\S]*?" + escapeRegExp(END));
if (!region.test(readme)) {
  console.error("Gallery markers not found in README.md");
  process.exit(1);
}
const updated = readme.replace(region, block);

if (checkOnly) {
  if (updated !== readme) {
    console.error(
      "README gallery is out of date. Run `npm run gallery` and commit README.md."
    );
    process.exit(1);
  }
  console.log(
    `README gallery is up to date (${withFx.length} with effects, ${classic.length} classic).`
  );
} else {
  writeFileSync(readmePath, updated);
  console.log(
    `Updated README gallery (${withFx.length} with effects, ${classic.length} classic).`
  );
}
